### ISSUE TITLE
The sensor stop to work

### ISSUE THREAD

**Issue by jesterino** [AlgorithmicEntropy/SolarWattHassio#6]
Home Assistant 2022.8.6
Supervisor 2023.03.1
Operating System 9.5
Frontend 20220802.0 - latest

The Integration Says a Red ! Retrying setup: None
every sensors are unavailable

in the LOG:
Logger: custom_components.solar_watt_energy_manager
Source: custom_components/solar_watt_energy_manager/__init__.py:74
Integration: SolarWattEnergyManager ([documentation](https://github.com/SebastianWallat/SolarWattHassio), [issues](https://github.com/SebastianWallat/SolarWattHassio/issues))
First occurred: 21:50:26 (19 occurrences)
Last logged: 22:10:25

EnergyManager Sensor has no data, unable to set up

**Comment by AlgorithmicEntropy** [comment]
Seems like the EnergyManager (kiwigrid) api has changed.. which broke the integration

**Comment by AlgorithmicEntropy** [comment]
Please update to newest version of the integration, this should fix your issue

**Comment by jesterino** [comment]
I got this error after updatedGianfranco PanicoIl giorno 10 mar 2023, alle ore 20:36, AlgorithmicEntropy ***@***.***> ha scritto:﻿
Please update to newest version of the integration, this should fix your issue

**Comment by AlgorithmicEntropy** [comment]
Are you shure you are on version 0.2.2 of the custom integration?

**Comment by jesterino** [comment]
I had to update HA to latest 2023 versionI used old 2022 before they changed rest sensor commands Now it workThank you Gianfranco PanicoIl giorno 11 mar 2023, alle ore 16:44, AlgorithmicEntropy ***@***.***> ha scritto:﻿
Reopened #6.
